//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavodApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int idNews { get; set; }
        public Nullable<int> idAdmin { get; set; }
        public string title { get; set; }
        public string textNews { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
