//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavodApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportCard()
        {
            this.ReportBrak = new HashSet<ReportBrak>();
        }
    
        public Nullable<int> idDetail { get; set; }
        public Nullable<int> idWorker { get; set; }
        public Nullable<int> numberOfDetails { get; set; }
        public int idReportCard { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> workingTime { get; set; }
    
        public virtual Detail Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportBrak> ReportBrak { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
